/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemaGestionRRHHHPresentacion;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author alecg
 */
public class DialogDepartamento extends javax.swing.JDialog {

    /**
     * Creates new form Departamento
     */
    public DialogDepartamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("CompuWork - Sistema de Gestión de RRHH");
        this.setLocationRelativeTo(null);
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/sistemaGestionRRHH.Images/tienda2025.png")).getImage());
        } catch (Exception e) {
            System.out.println("ERROR AL CARGAR LA IMAGEN");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMostrarDepartamentos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarDepartamento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnActualizarDepartamentos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 401));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(4, 78, 32));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión Departamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnMostrarDepartamentos.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarDepartamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarDepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarDepartamentosMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaGestionRRHH.Images/departamento.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(4, 78, 32));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 78, 32));
        jLabel5.setText("Mostrar Departamentos");

        javax.swing.GroupLayout btnMostrarDepartamentosLayout = new javax.swing.GroupLayout(btnMostrarDepartamentos);
        btnMostrarDepartamentos.setLayout(btnMostrarDepartamentosLayout);
        btnMostrarDepartamentosLayout.setHorizontalGroup(
            btnMostrarDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarDepartamentosLayout.createSequentialGroup()
                .addGroup(btnMostrarDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMostrarDepartamentosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(btnMostrarDepartamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btnMostrarDepartamentosLayout.setVerticalGroup(
            btnMostrarDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAgregarDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarDepartamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarDepartamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarDepartamentoMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaGestionRRHH.Images/AgregarDepartamento.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 78, 32));
        jLabel6.setText("Agregar Departamento");

        javax.swing.GroupLayout btnAgregarDepartamentoLayout = new javax.swing.GroupLayout(btnAgregarDepartamento);
        btnAgregarDepartamento.setLayout(btnAgregarDepartamentoLayout);
        btnAgregarDepartamentoLayout.setHorizontalGroup(
            btnAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarDepartamentoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(55, 55, 55))
            .addGroup(btnAgregarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarDepartamentoLayout.setVerticalGroup(
            btnAgregarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnActualizarDepartamentos.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarDepartamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarDepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarDepartamentosMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemaGestionRRHH.Images/actualizar.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(4, 78, 32));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(4, 78, 32));
        jLabel7.setText("Actualizar Departamento");

        javax.swing.GroupLayout btnActualizarDepartamentosLayout = new javax.swing.GroupLayout(btnActualizarDepartamentos);
        btnActualizarDepartamentos.setLayout(btnActualizarDepartamentosLayout);
        btnActualizarDepartamentosLayout.setHorizontalGroup(
            btnActualizarDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarDepartamentosLayout.createSequentialGroup()
                .addGroup(btnActualizarDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnActualizarDepartamentosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(btnActualizarDepartamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnActualizarDepartamentosLayout.setVerticalGroup(
            btnActualizarDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnMostrarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAgregarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnActualizarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarDepartamentosMouseClicked
        System.out.print("mostrar menu empleados");
    }//GEN-LAST:event_btnMostrarDepartamentosMouseClicked

    private void btnMostrarDepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarDepartamentosMouseEntered
        this.mouseEntered(btnMostrarDepartamentos);
    }//GEN-LAST:event_btnMostrarDepartamentosMouseEntered

    private void btnMostrarDepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarDepartamentosMouseExited
        this.mouseExited(btnMostrarDepartamentos);
    }//GEN-LAST:event_btnMostrarDepartamentosMouseExited

    private void btnAgregarDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarDepartamentoMouseClicked
        System.out.print("mostrar menu empleados");
    }//GEN-LAST:event_btnAgregarDepartamentoMouseClicked

    private void btnAgregarDepartamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarDepartamentoMouseEntered
        this.mouseEntered(btnAgregarDepartamento);
    }//GEN-LAST:event_btnAgregarDepartamentoMouseEntered

    private void btnAgregarDepartamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarDepartamentoMouseExited
        this.mouseExited(btnAgregarDepartamento);
    }//GEN-LAST:event_btnAgregarDepartamentoMouseExited

    private void btnActualizarDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDepartamentosMouseClicked
        System.out.print("mostrar menu empleados");
    }//GEN-LAST:event_btnActualizarDepartamentosMouseClicked

    private void btnActualizarDepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDepartamentosMouseEntered
        this.mouseEntered(btnActualizarDepartamentos);
    }//GEN-LAST:event_btnActualizarDepartamentosMouseEntered

    private void btnActualizarDepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDepartamentosMouseExited
        this.mouseExited(btnActualizarDepartamentos);
    }//GEN-LAST:event_btnActualizarDepartamentosMouseExited

    private void mouseEntered(JPanel panel) {
    panel.setBackground(new Color(191, 255, 215));
}
    private void mouseExited(JPanel panel) {
    panel.setBackground(new Color(255, 244, 255));
}
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizarDepartamentos;
    private javax.swing.JPanel btnAgregarDepartamento;
    private javax.swing.JPanel btnMostrarDepartamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
